name: Crawling the stock price

on:
  push:
    branches: [ main ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U finance-datareader
    - name: Crawling the stock price
      run: |
        python ./price-crawling/finance-data-reader.py